[build]
  publish = "."

[[build.environment]]
  NODE_VERSION = "20"

[[redirects]]
  from = "/pulses"
  to = "/devlog.html"
  status = 301

[forms.contact-form]
  name = "Contact Form"

[forms.contact-form.notifications]
  to = "danielthelober@gmail.com"
  from = "danielthelober@gmail.com"
  subject = "New Uplink Signal: {{formData.subject}}"
  body = """
Name: {{formData.name}}
Email: {{formData.email}}
Subject: {{formData.subject}}

Message:
{{formData.message}}
  """
